apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-clusterrole.yml
- grafana-clusterrolebind.yml
- grafana-role.yml
- grafana-rolebinding.yml
- otel-collector-clusterrole.yml
- otel-collector-clusterrolebinding.yml
- prometheus-clusterrole.yml
- prometheus-clusterrolebinding.yml
