apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
  labels:
    helm.sh/chart: opentelemetry-demo-0.40.7
    app.kubernetes.io/version: 2.2.0
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
    grafana_datasource: '1'
data:
  default.yaml: "# Copyright The OpenTelemetry Authors\n# SPDX-License-Identifier:\
    \ Apache-2.0\n\n\napiVersion: 1\n\ndatasources:\n  - name: Prometheus\n    uid:\
    \ webstore-metrics\n    type: prometheus\n    url: http://prometheus:9090\n  \
    \  editable: true\n    isDefault: true\n    jsonData:\n      # Align Prometheus\
    \ data source time interval with the OTel SDKs' export interval (see OTEL_METRIC_EXPORT_INTERVAL)\n\
    \      timeInterval: \"60s\"\n      exemplarTraceIdDestinations:\n        - datasourceUid:\
    \ webstore-traces\n          name: trace_id\n\n        - url: http://localhost:8080/jaeger/ui/trace/$${__value.raw}\n\
    \          name: trace_id\n          urlDisplayLabel: View in Jaeger UI\n"
  jaeger.yaml: "# Copyright The OpenTelemetry Authors\n# SPDX-License-Identifier:\
    \ Apache-2.0\n\n\napiVersion: 1\n\ndatasources:\n  - name: Jaeger\n    uid: webstore-traces\n\
    \    type: jaeger\n    url: http://jaeger:16686/jaeger/ui\n    editable: true\n\
    \    isDefault: false\n    jsonData:\n      tracesToLogsV2:\n        datasourceUid:\
    \ webstore-logs\n        spanStartTimeShift: \"-20m\"\n        spanEndTimeShift:\
    \ \"20m\"\n        filterByTraceID: true\n        filterBySpanID: true\n     \
    \   customQuery: true\n        query: traceId:\"$${__trace.traceId}\" AND spanId:\"\
    $${__span.spanId}\"\n"
  opensearch.yaml: "# Copyright The OpenTelemetry Authors\n# SPDX-License-Identifier:\
    \ Apache-2.0\n\napiVersion: 1\n\ndatasources:\n  - name: OpenSearch\n    uid:\
    \ webstore-logs\n    type: grafana-opensearch-datasource\n    url: http://opensearch:9200/\n\
    \    access: proxy\n    editable: true\n    isDefault: false\n    jsonData:\n\
    \      database: otel-logs-*\n      flavor: opensearch\n      logLevelField: severity.text.keyword\n\
    \      logMessageField: body\n      pplEnabled: true\n      timeField: observedTimestamp\n\
    \      version: 3.4.0\n"
