apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: my-otel-demo
    app.kubernetes.io/version: v3.9.0
    helm.sh/chart: prometheus-28.2.0
    app.kubernetes.io/part-of: prometheus
  name: prometheus
  namespace: default
data:
  allow-snippet-annotations: 'false'
  alerting_rules.yml: '{}

    '
  alerts: '{}

    '
  prometheus.yml: "global:\n  evaluation_interval: 1m\n  scrape_interval: 1m\n  scrape_timeout:\
    \ 10s\nstorage:\n  tsdb:\n    out_of_order_time_window: 30m\notlp:\n    keep_identifying_resource_attributes:\
    \ true\n    promote_resource_attributes:\n    - service.instance.id\n    - service.name\n\
    \    - service.namespace\n    - service.version\n    - cloud.availability_zone\n\
    \    - cloud.region\n    - deployment.environment.name\n    - k8s.cluster.name\n\
    \    - k8s.container.name\n    - k8s.cronjob.name\n    - k8s.daemonset.name\n\
    \    - k8s.deployment.name\n    - k8s.job.name\n    - k8s.namespace.name\n   \
    \ - k8s.node.name\n    - k8s.pod.name\n    - k8s.replicaset.name\n    - k8s.statefulset.name\n\
    \    - container.name\n    - host.name\n    - postgresql.database.name\n    -\
    \ postgresql.schema.name\n    - postgresql.table.name\n    - postgresql.index.name\n\
    scrape_configs:\n- job_name: kubernetes-api-servers\n  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n\
    \  kubernetes_sd_configs:\n  - role: endpoints\n  relabel_configs:\n  - action:\
    \ keep\n    regex: default;kubernetes;https\n    source_labels:\n    - __meta_kubernetes_namespace\n\
    \    - __meta_kubernetes_service_name\n    - __meta_kubernetes_endpoint_port_name\n\
    \  scheme: https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    - job_name: kubernetes-nodes\n  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n\
    \  kubernetes_sd_configs:\n  - role: node\n  relabel_configs:\n  - action: labelmap\n\
    \    regex: __meta_kubernetes_node_label_(.+)\n  - replacement: kubernetes.default.svc:443\n\
    \    target_label: __address__\n  - regex: (.+)\n    replacement: /api/v1/nodes/$1/proxy/metrics\n\
    \    source_labels:\n    - __meta_kubernetes_node_name\n    target_label: __metrics_path__\n\
    \  scheme: https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    - job_name: kubernetes-nodes-cadvisor\n  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n\
    \  kubernetes_sd_configs:\n  - role: node\n  relabel_configs:\n  - action: labelmap\n\
    \    regex: __meta_kubernetes_node_label_(.+)\n  - replacement: kubernetes.default.svc:443\n\
    \    target_label: __address__\n  - regex: (.+)\n    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor\n\
    \    source_labels:\n    - __meta_kubernetes_node_name\n    target_label: __metrics_path__\n\
    \  scheme: https\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n\
    - job_name: kubernetes-pods\n  honor_labels: true\n  kubernetes_sd_configs:\n\
    \  - role: pod\n  relabel_configs:\n  - action: keep\n    regex: true\n    source_labels:\n\
    \    - __meta_kubernetes_pod_annotation_prometheus_io_scrape\n  - action: drop\n\
    \    regex: true\n    source_labels:\n    - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow\n\
    \  - action: replace\n    regex: (https?)\n    source_labels:\n    - __meta_kubernetes_pod_annotation_prometheus_io_scheme\n\
    \    target_label: __scheme__\n  - action: replace\n    regex: (.+)\n    source_labels:\n\
    \    - __meta_kubernetes_pod_annotation_prometheus_io_path\n    target_label:\
    \ __metrics_path__\n  - action: replace\n    regex: (\\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})\n\
    \    replacement: '[$2]:$1'\n    source_labels:\n    - __meta_kubernetes_pod_annotation_prometheus_io_port\n\
    \    - __meta_kubernetes_pod_ip\n    target_label: __address__\n  - action: replace\n\
    \    regex: (\\d+);((([0-9]+?)(\\.|$)){4})\n    replacement: $2:$1\n    source_labels:\n\
    \    - __meta_kubernetes_pod_annotation_prometheus_io_port\n    - __meta_kubernetes_pod_ip\n\
    \    target_label: __address__\n  - action: labelmap\n    regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)\n\
    \    replacement: __param_$1\n  - action: labelmap\n    regex: __meta_kubernetes_pod_label_(.+)\n\
    \  - action: replace\n    source_labels:\n    - __meta_kubernetes_namespace\n\
    \    target_label: namespace\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_pod_name\n\
    \    target_label: pod\n  - action: drop\n    regex: Pending|Succeeded|Failed|Completed\n\
    \    source_labels:\n    - __meta_kubernetes_pod_phase\n  - action: replace\n\
    \    source_labels:\n    - __meta_kubernetes_pod_node_name\n    target_label:\
    \ node\n- job_name: kubernetes-pods-slow\n  honor_labels: true\n  kubernetes_sd_configs:\n\
    \  - role: pod\n  relabel_configs:\n  - action: keep\n    regex: true\n    source_labels:\n\
    \    - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow\n  - action:\
    \ replace\n    regex: (https?)\n    source_labels:\n    - __meta_kubernetes_pod_annotation_prometheus_io_scheme\n\
    \    target_label: __scheme__\n  - action: replace\n    regex: (.+)\n    source_labels:\n\
    \    - __meta_kubernetes_pod_annotation_prometheus_io_path\n    target_label:\
    \ __metrics_path__\n  - action: replace\n    regex: (\\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})\n\
    \    replacement: '[$2]:$1'\n    source_labels:\n    - __meta_kubernetes_pod_annotation_prometheus_io_port\n\
    \    - __meta_kubernetes_pod_ip\n    target_label: __address__\n  - action: replace\n\
    \    regex: (\\d+);((([0-9]+?)(\\.|$)){4})\n    replacement: $2:$1\n    source_labels:\n\
    \    - __meta_kubernetes_pod_annotation_prometheus_io_port\n    - __meta_kubernetes_pod_ip\n\
    \    target_label: __address__\n  - action: labelmap\n    regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)\n\
    \    replacement: __param_$1\n  - action: labelmap\n    regex: __meta_kubernetes_pod_label_(.+)\n\
    \  - action: replace\n    source_labels:\n    - __meta_kubernetes_namespace\n\
    \    target_label: namespace\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_pod_name\n\
    \    target_label: pod\n  - action: drop\n    regex: Pending|Succeeded|Failed|Completed\n\
    \    source_labels:\n    - __meta_kubernetes_pod_phase\n  - action: replace\n\
    \    source_labels:\n    - __meta_kubernetes_pod_node_name\n    target_label:\
    \ node\n  scrape_interval: 5m\n  scrape_timeout: 30s\n- job_name: kubernetes-service-endpoints\n\
    \  honor_labels: true\n  kubernetes_sd_configs:\n  - role: endpoints\n  relabel_configs:\n\
    \  - action: keep\n    regex: true\n    source_labels:\n    - __meta_kubernetes_service_annotation_prometheus_io_scrape\n\
    \  - action: drop\n    regex: true\n    source_labels:\n    - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow\n\
    \  - action: replace\n    regex: (https?)\n    source_labels:\n    - __meta_kubernetes_service_annotation_prometheus_io_scheme\n\
    \    target_label: __scheme__\n  - action: replace\n    regex: (.+)\n    source_labels:\n\
    \    - __meta_kubernetes_service_annotation_prometheus_io_path\n    target_label:\
    \ __metrics_path__\n  - action: replace\n    regex: (.+?)(?::\\d+)?;(\\d+)\n \
    \   replacement: $1:$2\n    source_labels:\n    - __address__\n    - __meta_kubernetes_service_annotation_prometheus_io_port\n\
    \    target_label: __address__\n  - action: labelmap\n    regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)\n\
    \    replacement: __param_$1\n  - action: labelmap\n    regex: __meta_kubernetes_service_label_(.+)\n\
    \  - action: replace\n    source_labels:\n    - __meta_kubernetes_namespace\n\
    \    target_label: namespace\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_service_name\n\
    \    target_label: service\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_pod_node_name\n\
    \    target_label: node\n- job_name: kubernetes-service-endpoints-slow\n  honor_labels:\
    \ true\n  kubernetes_sd_configs:\n  - role: endpoints\n  relabel_configs:\n  -\
    \ action: keep\n    regex: true\n    source_labels:\n    - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow\n\
    \  - action: replace\n    regex: (https?)\n    source_labels:\n    - __meta_kubernetes_service_annotation_prometheus_io_scheme\n\
    \    target_label: __scheme__\n  - action: replace\n    regex: (.+)\n    source_labels:\n\
    \    - __meta_kubernetes_service_annotation_prometheus_io_path\n    target_label:\
    \ __metrics_path__\n  - action: replace\n    regex: (.+?)(?::\\d+)?;(\\d+)\n \
    \   replacement: $1:$2\n    source_labels:\n    - __address__\n    - __meta_kubernetes_service_annotation_prometheus_io_port\n\
    \    target_label: __address__\n  - action: labelmap\n    regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)\n\
    \    replacement: __param_$1\n  - action: labelmap\n    regex: __meta_kubernetes_service_label_(.+)\n\
    \  - action: replace\n    source_labels:\n    - __meta_kubernetes_namespace\n\
    \    target_label: namespace\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_service_name\n\
    \    target_label: service\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_pod_node_name\n\
    \    target_label: node\n  scrape_interval: 5m\n  scrape_timeout: 30s\n- job_name:\
    \ kubernetes-services\n  honor_labels: true\n  kubernetes_sd_configs:\n  - role:\
    \ service\n  metrics_path: /probe\n  params:\n    module:\n    - http_2xx\n  relabel_configs:\n\
    \  - action: keep\n    regex: true\n    source_labels:\n    - __meta_kubernetes_service_annotation_prometheus_io_probe\n\
    \  - source_labels:\n    - __address__\n    target_label: __param_target\n  -\
    \ replacement: blackbox\n    target_label: __address__\n  - source_labels:\n \
    \   - __param_target\n    target_label: instance\n  - action: labelmap\n    regex:\
    \ __meta_kubernetes_service_label_(.+)\n  - source_labels:\n    - __meta_kubernetes_namespace\n\
    \    target_label: namespace\n  - source_labels:\n    - __meta_kubernetes_service_name\n\
    \    target_label: service\n- job_name: prometheus\n  static_configs:\n  - targets:\n\
    \    - localhost:9090\n- job_name: prometheus-pushgateway\n  honor_labels: true\n\
    \  kubernetes_sd_configs:\n  - role: service\n  relabel_configs:\n  - action:\
    \ keep\n    regex: pushgateway\n    source_labels:\n    - __meta_kubernetes_service_annotation_prometheus_io_probe\n\
    rule_files:\n- /etc/config/recording_rules.yml\n- /etc/config/alerting_rules.yml\n\
    - /etc/config/rules\n- /etc/config/alerts\n"
  recording_rules.yml: '{}

    '
  rules: '{}

    '
