apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- accounting-deployment.yml
- ad-deployment.yml
- cart-deployment.yml
- checkout-deployment.yml
- currency-deployment.yml
- email-deployment.yml
- flagd-deployment.yml
- fraud-detection-deployment.yml
- frontend-deployment.yml
- frontend-proxy-deployment.yml
- grafana-deployment.yml
- image-provider-deployment.yml
- jaeger-deployment.yml
- kafka-deployment.yml
- llm-deployment.yml
- load-generator-deployment.yml
- payment-deployment.yml
- postgresql-deployment.yml
- product-catalog-deployment.yml
- product-reviews-deployment.yml
- prometheus-deployment.yml
- quote-deployment.yml
- recommendation-deployment.yml
- shipping-deployment.yml
- valkey-cart-deployment.yml
