apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ad-service.yml
- cart-service.yml
- checkout-service.yml
- currency-service.yml
- email-service.yml
- flagd-service.yml
- frontend-proxy-service.yml
- frontend-service.yml
- grafana-service.yml
- image-provider-service.yml
- jaeger-service.yml
- kafka-service.yml
- llm-service.yml
- load-generator-service.yml
- opensearch-headless-service.yml
- opensearch-service.yml
- otel-collector-service.yml
- payment-service.yml
- postgresql-service.yml
- product-catalog-service.yml
- product-reviews-service.yml
- prometheus-service.yml
- quote-service.yml
- recommendation-service.yml
- shipping-service.yml
- valkey-cart-service.yml
