kind: Service
apiVersion: v1
metadata:
  name: opensearch-headless
  labels:
    helm.sh/chart: opensearch-3.4.0
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: my-otel-demo
    app.kubernetes.io/version: 3.4.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: opensearch
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: my-otel-demo
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  - name: metrics
    port: 9600
