name: Deploy OpenTelemetry on EKS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform init
      - name: Terraform Init
        run: |
          cd otel-terraform
          terraform init -reconfigure

      # Terraform apply
      - name: Terraform Apply
        run: |
          cd otel-terraform
          terraform apply -auto-approve

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      # Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-2 \
            --name $(terraform -chdir=otel-terraform output -raw cluster_name)

      # Deploy Kubernetes manifests
      - name: Deploy Kubernetes
        run: |
          kubectl apply -k kubernetes

      # Get frontend LoadBalancer URL
      - name: Get Frontend URL
        run: |
          echo "Waiting for frontend-proxy LoadBalancer..."

          for i in {1..30}; do
            HOST=$(kubectl get svc frontend-proxy \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ ! -z "$HOST" ]; then
              echo "================================="
              echo "Frontend URL:"
              echo "http://$HOST:8080"
              echo "================================="
              exit 0
            fi

            echo "Waiting... attempt $i"
            sleep 10
          done

          echo "LoadBalancer not ready"
          exit 1
